In [1]:
import pandas as pd
import random

In [2]:
C1 = [random.randrange(-200,200, 1) for i in range(1000)]
C2 = [random.randrange(-200,200, 1) for i in range(1000)]
C3 = [random.randrange(-200,200, 1) for i in range(1000)]
C4 = [random.randrange(-200,200, 1) for i in range(1000)]
V1 = [random.randrange(0,50, 1) for i in range(1000)]
V2 = [random.randrange(0,50, 1) for i in range(1000)]
V3 = [random.randrange(0,50, 1) for i in range(1000)]
V4 = [random.randrange(0,50, 1) for i in range(1000)]
#X1 = [random.randint(0, 1) for _ in range(1000)]
#X2 = [random.randint(0, 1) for _ in range(1000)]
#X3 = [random.randint(0, 1) for _ in range(1000)]
#X4 = [random.randint(0, 1) for _ in range(1000)]
X1 = []
X2 = []
X3 = []
X4 = []

In [3]:
for i in C1:
    if i<0:
        X1.append(0)
    else:
        X1.append(1)
        

In [4]:
for i in C2:
    if i<0:
        X2.append(0)
    else:
        X2.append(1)

In [5]:
for i in C3:
    if i<0:
        X3.append(0)
    else:
        X3.append(1)

In [6]:
for i in C4:
    if i<0:
        X4.append(0)
    else:
        X4.append(1)

In [7]:
C1

[15,
 -190,
 89,
 27,
 -113,
 -152,
 -191,
 -111,
 20,
 -121,
 65,
 -138,
 179,
 162,
 167,
 -44,
 -74,
 73,
 108,
 138,
 -73,
 128,
 67,
 89,
 126,
 -166,
 180,
 -84,
 189,
 170,
 180,
 -24,
 -190,
 62,
 -7,
 -111,
 19,
 34,
 109,
 73,
 -23,
 -53,
 134,
 122,
 -94,
 34,
 85,
 -101,
 100,
 -114,
 72,
 -33,
 -60,
 198,
 -69,
 -39,
 -8,
 62,
 10,
 127,
 -82,
 -80,
 114,
 -107,
 -93,
 -124,
 47,
 180,
 176,
 -102,
 35,
 194,
 -71,
 80,
 73,
 -59,
 14,
 -83,
 78,
 -29,
 105,
 -148,
 -169,
 -37,
 87,
 101,
 73,
 -170,
 -92,
 130,
 52,
 -156,
 -109,
 115,
 119,
 -135,
 -59,
 89,
 -26,
 -22,
 -173,
 146,
 91,
 150,
 151,
 67,
 -13,
 -117,
 -47,
 -9,
 -85,
 -99,
 -138,
 -143,
 -192,
 -184,
 -67,
 129,
 146,
 -102,
 -80,
 19,
 122,
 -56,
 -10,
 -142,
 135,
 -125,
 -107,
 162,
 34,
 158,
 -193,
 -42,
 -60,
 -197,
 -33,
 151,
 24,
 78,
 77,
 -102,
 -154,
 -184,
 -4,
 -36,
 -67,
 22,
 11,
 -102,
 -34,
 78,
 -181,
 83,
 153,
 183,
 -131,
 101,
 149,
 148,
 120,
 76,
 -156,
 47,
 113,
 92,
 -142,
 4

In [8]:
X1

[1,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 0,


In [2]:
import tensorflow as tf
import numpy
from sklearn.model_selection import train_test_split
from tensorflow.python.framework.ops import disable_eager_execution
#tf.enable_eager_execution()
disable_eager_execution()

In [3]:
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense

In [11]:
df = pd.DataFrame({'col1':C1,'col2':C2,'col3':C3,'col4':C4,'col5':V1,'col6':V2,'col7':V3,'col8':V4,'col9':X1,'col10':X2,'col11':X3,'col12':X4})

In [12]:
df

col1  col2  col3  col4  col5  col6  col7  col8  col9  col10  col11  col12
0      15    93    28  -131    33    33    31     1     1      1      1      0
1    -190  -173   128   -25    11    22    16    24     0      0      1      0
2      89    48  -155   165    16    18    15     7     1      1      0      1
3      27   -17  -193    -7    28    30     8    34     1      0      0      0
4    -113   -63  -116  -133    45     7    47    38     0      0      0      0
..    ...   ...   ...   ...   ...   ...   ...   ...   ...    ...    ...    ...
995    90   147   -68  -196    14    42    29    36     1      1      0      0
996  -187   172   -56   -38    37    37     9     9     0      1      0      0
997    -7  -165    26   114    42    16    20    10     0      0      1      1
998    22  -182   145    87    25    11    33    14     1      0      1      1
999   102   122   192    84     5    21    37    35     1      1      1      1

[1000 rows x 12 columns]

In [13]:
X_1 = df.iloc[:,:4].values

In [14]:
X_1  = X_1.astype('float32')

In [15]:
X_2 = df.iloc[:,4:8].values

In [16]:
X_2 = X_2.astype('float32')

In [17]:
y = df.iloc[:,8:].values

In [18]:
y = y.astype('float32')

In [19]:
X_1

array([[  15.,   93.,   28., -131.],
       [-190., -173.,  128.,  -25.],
       [  89.,   48., -155.,  165.],
       ...,
       [  -7., -165.,   26.,  114.],
       [  22., -182.,  145.,   87.],
       [ 102.,  122.,  192.,   84.]], dtype=float32)

In [20]:
X_2

array([[33., 33., 31.,  1.],
       [11., 22., 16., 24.],
       [16., 18., 15.,  7.],
       ...,
       [42., 16., 20., 10.],
       [25., 11., 33., 14.],
       [ 5., 21., 37., 35.]], dtype=float32)

In [21]:
X1_train, X1_test, X2_train, X2_test,y_train, y_test = train_test_split(X_1,X_2, y, test_size=0.33, random_state=42)

In [22]:
X1_train

array([[ 156.,    2.,   84., -144.],
       [  38.,  143.,   64.,   20.],
       [ 147.,  -34.,  116., -142.],
       ...,
       [ -79., -100.,  195.,  -39.],
       [-195., -180.,   98.,  -66.],
       [  91.,    7.,  118.,  148.]], dtype=float32)

In [23]:
X2_train

array([[21., 12., 44., 23.],
       [ 1., 15., 23., 38.],
       [35.,  2., 21., 24.],
       ...,
       [ 8., 17., 27.,  0.],
       [28., 39., 30., 41.],
       [13., 43., 18.,  5.]], dtype=float32)

In [27]:
def custom_loss(X1,X2,l):
    def loss(y_true,y_pred):
        return -1*(K.batch_dot(X1,y_pred,1)) + ((l)*(K.maximum((K.batch_dot(X2,y_pred,1) - 10),0)))
    return loss

In [4]:
from tensorflow.keras.layers import Input, Dense, Activation,Dropout
from tensorflow.keras.models import Model
#import tensorflow.keras.callbacks.ReduceLROnPlateau

In [29]:
X1 = tf.keras.Input((4,),name = "X1")
X2 = tf.keras.Input((4,),name = "X2")
inputs_concat = tf.keras.layers.Concatenate(name="Concatenate")([X1, X2])
picks = tf.keras.layers.Dense(32, activation="relu", name="Hidden1")(inputs_concat)
picks = tf.keras.layers.Dense(8, activation="relu", name="Hidden2")(picks)
picks = tf.keras.layers.Dense(4, activation="sigmoid", name="Output")(picks)
model = tf.keras.Model(inputs=[X1,X2], outputs=[picks])
model.compile(tf.keras.optimizers.Adam(lr=0.001),loss = custom_loss(X1,X2,0.1),experimental_run_tf_function=False)
print(model.summary())

Model: "model_1"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
X1 (InputLayer)                 [(None, 4)]          0                                            
__________________________________________________________________________________________________
X2 (InputLayer)                 [(None, 4)]          0                                            
__________________________________________________________________________________________________
Concatenate (Concatenate)       (None, 8)            0           X1[0][0]                         
                                                                 X2[0][0]                         
__________________________________________________________________________________________________
Hidden1 (Dense)                 (None, 32)           288         Concatenate[0][0]          

In [5]:
import tensorflow.keras.backend as K

In [31]:
model.fit([X1_train,X2_train], y_train, epochs=150, verbose=1)

Train on 670 samples
Epoch 1/150
670/670 [==============================] - 0s 320us/sample - loss: -22.6164
Epoch 2/150
670/670 [==============================] - 0s 39us/sample - loss: -47.5116
Epoch 3/150
670/670 [==============================] - 0s 40us/sample - loss: -62.7915
Epoch 4/150
670/670 [==============================] - 0s 40us/sample - loss: -78.3787
Epoch 5/150
670/670 [==============================] - 0s 39us/sample - loss: -94.9773
Epoch 6/150
670/670 [==============================] - 0s 40us/sample - loss: -108.1178
Epoch 7/150
670/670 [==============================] - 0s 40us/sample - loss: -113.9855
Epoch 8/150
670/670 [==============================] - 0s 39us/sample - loss: -122.3134
Epoch 9/150
670/670 [==============================] - 0s 42us/sample - loss: -128.6112
Epoch 10/150
670/670 [==============================] - 0s 40us/sample - loss: -132.5833
Epoch 11/150
670/670 [==============================] - 0s 39us/sample - loss: -135.7041
Epoch 12/150


Epoch 93/150
670/670 [==============================] - 0s 34us/sample - loss: -143.9965
Epoch 94/150
670/670 [==============================] - 0s 33us/sample - loss: -143.9966
Epoch 95/150
670/670 [==============================] - 0s 33us/sample - loss: -143.9991
Epoch 96/150
670/670 [==============================] - ETA: 0s - loss: -112.16 - 0s 33us/sample - loss: -144.0004
Epoch 97/150
670/670 [==============================] - 0s 31us/sample - loss: -144.0048
Epoch 98/150
670/670 [==============================] - 0s 31us/sample - loss: -144.0089
Epoch 99/150
670/670 [==============================] - 0s 34us/sample - loss: -144.0093
Epoch 100/150
670/670 [==============================] - 0s 34us/sample - loss: -144.0133
Epoch 101/150
670/670 [==============================] - 0s 31us/sample - loss: -144.0145
Epoch 102/150
670/670 [==============================] - 0s 31us/sample - loss: -144.0179
Epoch 103/150
670/670 [==============================] - 0s 31us/sample - loss: -

In [32]:
p = model.predict([X1_test,X2_test])

c:\users\venkat\appdata\local\programs\python\python39\lib\site-packages\keras\engine\training.py:2470: UserWarning: `Model.state_updates` will be removed in a future version. This property should not be used in TensorFlow 2.0, as `updates` are applied automatically.
  warnings.warn('`Model.state_updates` will be removed in a future version. '


In [33]:
p.round()

array([[1., 1., 0., 0.],
       [1., 1., 0., 1.],
       [0., 1., 1., 0.],
       ...,
       [1., 1., 1., 1.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.]], dtype=float32)

In [34]:
y_test

array([[1., 0., 0., 0.],
       [1., 0., 0., 1.],
       [0., 1., 1., 0.],
       ...,
       [1., 0., 1., 1.],
       [0., 0., 0., 1.],
       [0., 0., 0., 1.]], dtype=float32)

In [35]:
X1_test[150]

array([ 98.,  94., 104.,  59.], dtype=float32)

In [36]:
X2_test[150]

array([36., 12., 15., 20.], dtype=float32)

In [37]:
y_test[150]

array([1., 1., 1., 1.], dtype=float32)

In [38]:
p[150].round()

array([1., 1., 1., 1.], dtype=float32)

In [39]:
X1_test[120]

array([-129.,    8.,  133.,  -31.], dtype=float32)

In [40]:
X2_test[120]

array([36., 36., 45., 16.], dtype=float32)

In [41]:
y_test[120]

array([0., 1., 1., 0.], dtype=float32)

In [42]:
p[120].round()

array([0., 1., 1., 0.], dtype=float32)

## Knapsack

In [6]:
import numpy as np
import pandas as pd
import math

In [7]:

def brute_force_knapsack(x_weights, x_prices, x_capacity):
    item_count = x_weights.shape[0]
    picks_space = 2 ** item_count
    best_price = -1
    best_picks = np.zeros(item_count)
    for p in range(picks_space):
        picks = [int(c) for c in f"{p:0{item_count}b}"]
        price = np.dot(x_prices, picks)
        weight = np.dot(x_weights, picks)
        if weight <= x_capacity and price > best_price:
            best_price = price
            best_picks = picks
    return best_picks


def create_knapsack(item_count=5):
    x_weights = np.random.uniform(1,45, item_count)
    x_prices = np.random.uniform(1,45, item_count)
    x_capacity = np.random.uniform(1,99)
    y = brute_force_knapsack(x_weights, x_prices, x_capacity)
    return x_weights, x_prices, x_capacity, y

In [8]:
from keras.layers import Dense, Activation, Lambda, Input, Concatenate, Multiply, Add

In [9]:
create_knapsack(10)

(array([27.47085368, 28.97967514, 33.33140789, 35.5230017 , 10.29520333,
        36.85387481,  5.99515172, 21.53965783, 40.5166529 , 34.42761734]),
 array([29.53801671, 33.77389859, 15.94319523,  7.28835869, 35.31116312,
        12.0168881 , 37.38156569,  9.86113964, 13.79580212, 39.56545101]),
 5.649013411956723,
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [10]:
dataset = []

In [11]:
for i in range(100000):
    dataset.append(create_knapsack(5))

In [12]:
len(dataset)

100000

In [13]:
dataset_n = dataset

In [14]:
dataset_n

[(array([16.58561462, 41.76864978, 43.39825938, 34.58252041, 42.12134479]),
  array([33.35851329, 31.70636311, 26.45348063, 25.96315501, 22.78951169]),
  50.70986824217104,
  [1, 0, 0, 0, 0]),
 (array([38.73705476, 30.9093836 ,  9.61934489, 22.66716381, 13.42153932]),
  array([29.10803366, 13.92439166,  1.07256179,  6.84363723, 24.28684003]),
  33.26580361411213,
  [0, 0, 1, 0, 1]),
 (array([ 7.04558393,  5.23782551, 28.33128852, 43.9516614 , 41.58333547]),
  array([35.64381311,  6.63508203,  3.4313358 , 44.62519933, 20.00005619]),
  37.26511196942485,
  [1, 1, 0, 0, 0]),
 (array([26.62203776, 16.25396247, 43.56622542,  2.90836119, 44.69025242]),
  array([28.78237436,  1.28152389, 20.32646084,  5.14690241, 31.76711956]),
  76.23312108114354,
  [1, 0, 0, 1, 1]),
 (array([40.76927048,  3.45313286, 28.70544932, 15.82118398, 35.35352116]),
  array([17.43270166,  5.30191759, 10.47780708,  3.13461195, 43.88021695]),
  67.65895538687097,
  [0, 1, 1, 0, 1]),
 (array([ 8.98296612, 29.62016111, 

In [15]:
weights_list = []

In [16]:
for i in dataset_n:
    weights_list.append(i[0])

In [17]:
weights_arr = np.array(weights_list)

In [18]:
weights_arr

array([[16.58561462, 41.76864978, 43.39825938, 34.58252041, 42.12134479],
       [38.73705476, 30.9093836 ,  9.61934489, 22.66716381, 13.42153932],
       [ 7.04558393,  5.23782551, 28.33128852, 43.9516614 , 41.58333547],
       ...,
       [ 1.8147048 , 10.37794862, 34.6621455 , 24.05417507, 25.4204613 ],
       [35.11635362, 14.99553316, 10.24500369, 22.75397555, 34.5793391 ],
       [23.36366448, 13.5198045 , 21.84557693, 11.99436579, 17.86673309]])

In [19]:
prices_list = []
for i in dataset_n:
    prices_list.append(i[1])
prices_arr = np.array(prices_list)

In [20]:
optimal_list = []
for i in dataset_n:
    optimal_list.append(i[3])
optimal_arr = np.array(optimal_list)

In [21]:
cap_list = []
for i in dataset_n:
    cap_list.append(i[2])
cap_arr = np.array(cap_list)

In [22]:
cap_arr

array([50.70986824, 33.26580361, 37.26511197, ..., 66.55928819,
       59.66599128, 61.90577921])

In [23]:
weights_arr = weights_arr.astype('float32')
prices_arr = prices_arr.astype('float32')
optimal_arr = optimal_arr.astype('float32')
cap_arr = cap_arr.astype('float32')

In [24]:
prices_arr.shape

(100000, 5)

In [25]:
#weights_train, weights_test, prices_train, prices_test,y_train, y_test = train_test_split(weights_arr,prices_arr,optimal_arr, test_size=0.33, random_state=42)

In [26]:
weights_train = weights_arr[:70000,]
prices_train = prices_arr[:70000,]
cap_train = cap_arr[:70000,]
y_train = optimal_arr[:70000,]

weights_test = weights_arr[70000:,]
prices_test = prices_arr[70000:,]
cap_test = cap_arr[70000:,]
y_test = optimal_arr[70000:,]

In [72]:
def knapsack_new_loss(weights,prices,cap,alpha):
    def loss(y_true,y_pred):
        #y_pred = K.round(y_pred)
        #return K.mean(tf.square(K.batch_dot(y_pred, prices, 1) - K.batch_dot(y_true, prices, 1))) + (alpha*(K.mean(K.maximum(((K.batch_dot(y_pred,weights,1)) - cap),0))))
        return K.mean((-1*(K.batch_dot(y_pred, prices, 1))) + (alpha*((K.maximum(K.batch_dot(weights,(y_pred),1) - cap,0)))))
    
    return loss

In [73]:
def metric_overprice(prices):
    def overpricing(y_true, y_pred):
        y_pred = K.round(y_pred)
        return K.mean(K.batch_dot(y_pred, prices, 1) - K.batch_dot(y_true, prices, 1))

    return overpricing

In [74]:
def metric_space_violation(weights,cap):
    def space_violation(y_true, y_pred):
        y_pred = K.round(y_pred)
        return K.mean(K.maximum(K.batch_dot(y_pred, weights, 1) - cap, 0))

    return space_violation

In [75]:
weights_dict = {}

weight_callback = tf.keras.callbacks.LambdaCallback \
( on_epoch_end=lambda epoch, logs: weights_dict.update({epoch:model.get_weights()}))

In [76]:
weights = tf.keras.Input((5,),name = "weights")
prices = tf.keras.Input((5,),name = "prices")
cap = tf.keras.Input((1,),name = "cap")
inputs_concat = tf.keras.layers.Concatenate(name="Concatenate")([weights, prices,cap])
picks = tf.keras.layers.Dense(128, activation="relu", name="Hidden1")(inputs_concat)
#picks = tf.keras.layers.Dense(64, activation="sigmoid", name="Hidden2")(picks)
picks = tf.keras.layers.Dense(5, activation="sigmoid", name="Output")(picks)
model = tf.keras.Model(inputs=[weights,prices,cap], outputs=[picks])
model.compile(tf.keras.optimizers.Adam(lr=0.001),loss = knapsack_new_loss(weights,prices,cap,(10)),metrics = [metric_overprice(prices),metric_space_violation(weights,cap)],experimental_run_tf_function=False)
print(model.summary())

Model: "model_4"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
weights (InputLayer)            [(None, 5)]          0                                            
__________________________________________________________________________________________________
prices (InputLayer)             [(None, 5)]          0                                            
__________________________________________________________________________________________________
cap (InputLayer)                [(None, 1)]          0                                            
__________________________________________________________________________________________________
Concatenate (Concatenate)       (None, 11)           0           weights[0][0]                    
                                                                 prices[0][0]               

c:\users\venkat\appdata\local\programs\python\python39\lib\site-packages\keras\optimizer_v2\optimizer_v2.py:355: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  warnings.warn(


In [77]:
y_train.shape

(70000, 5)

In [78]:
cap_train.shape

(70000,)

In [79]:
reduce_lr = tf.keras.callbacks.ReduceLROnPlateau(monitor='val_loss', factor=0.2,
                              patience=5, min_lr=0.001)

In [80]:
history = model.fit([weights_train,prices_train,cap_train], y_train,validation_data = ([weights_test,prices_test,cap_test], y_test),epochs=50,batch_size =128 ,verbose=1,shuffle =True,callbacks=[reduce_lr])

Train on 70000 samples, validate on 30000 samples
Epoch 1/50
68608/70000 [============================>.] - ETA: 0s - loss: -104.1543 - overpricing: 47.7082 - space_violation: 64.6514

c:\users\venkat\appdata\local\programs\python\python39\lib\site-packages\keras\engine\training.py:2470: UserWarning: `Model.state_updates` will be removed in a future version. This property should not be used in TensorFlow 2.0, as `updates` are applied automatically.
  warnings.warn('`Model.state_updates` will be removed in a future version. '


70000/70000 [==============================] - 2s 28us/sample - loss: -104.2400 - overpricing: 47.7596 - space_violation: 64.6912 - val_loss: -107.0814 - val_overpricing: 49.0945 - val_space_violation: 65.4948 - lr: 0.0010
Epoch 2/50
70000/70000 [==============================] - 1s 17us/sample - loss: -107.7016 - overpricing: 49.1969 - space_violation: 65.9969 - val_loss: -107.0815 - val_overpricing: 49.0819 - val_space_violation: 65.4771 - lr: 0.0010
Epoch 3/50
70000/70000 [==============================] - 1s 17us/sample - loss: -107.7017 - overpricing: 49.1981 - space_violation: 65.9979 - val_loss: -107.0815 - val_overpricing: 49.1060 - val_space_violation: 65.4807 - lr: 0.0010
Epoch 4/50
70000/70000 [==============================] - 1s 18us/sample - loss: -107.7017 - overpricing: 49.1974 - space_violation: 65.9970 - val_loss: -107.0815 - val_overpricing: 49.0768 - val_space_violation: 65.4623 - lr: 0.0010
Epoch 5/50
70000/70000 [==============================] - 1s 17us/sample - 

Epoch 36/50
70000/70000 [==============================] - 1s 16us/sample - loss: -107.7017 - overpricing: 49.1973 - space_violation: 65.9973 - val_loss: -107.0815 - val_overpricing: 49.0742 - val_space_violation: 65.4542 - lr: 0.0010
Epoch 37/50
70000/70000 [==============================] - 1s 16us/sample - loss: -107.7017 - overpricing: 49.1968 - space_violation: 65.9967 - val_loss: -107.0815 - val_overpricing: 49.0724 - val_space_violation: 65.4599 - lr: 0.0010
Epoch 38/50
70000/70000 [==============================] - 1s 17us/sample - loss: -107.7017 - overpricing: 49.1965 - space_violation: 65.9959 - val_loss: -107.0815 - val_overpricing: 49.0883 - val_space_violation: 65.4684 - lr: 0.0010
Epoch 39/50
70000/70000 [==============================] - 1s 16us/sample - loss: -107.7017 - overpricing: 49.1968 - space_violation: 65.9972 - val_loss: -107.0815 - val_overpricing: 49.1121 - val_space_violation: 65.4886 - lr: 0.0010
Epoch 40/50
70000/70000 [==============================] - 1

In [ ]:
alpha = 0.0
step_size = 0.01 
for i in range(300): 
    model.compile(tf.keras.optimizers.Adam(lr=0.001),loss = knapsack_new_loss(weights,prices,cap,(alpha)),metrics = [metric_overprice(prices),metric_space_violation(weights,cap)],experimental_run_tf_function=False)
    history = model.fit([weights_train,prices_train,cap_train], y_train,validation_data = ([weights_test,prices_test,cap_test], y_test),epochs=1,batch_size =128 ,verbose=1,shuffle =True,callbacks=[reduce_lr])
    #val = (history.history['space_violation'][0])
    alpha = alpha + 1

In [64]:
p = model.predict([weights_train,prices_train,cap_train])

In [65]:
y_train

array([[1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 1.],
       [1., 1., 0., 0., 0.],
       ...,
       [0., 0., 1., 1., 1.],
       [1., 0., 0., 1., 0.],
       [1., 0., 0., 0., 1.]], dtype=float32)

In [66]:
p.round()

array([[1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1.],
       [1., 1., 0., 0., 0.],
       ...,
       [0., 1., 1., 1., 0.],
       [1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 1.]], dtype=float32)

In [67]:
weights_test

array([[29.07872  ,  5.9504128,  5.714783 , 44.347652 ,  4.122032 ],
       [37.841206 , 11.6405115, 43.92185  , 38.27272  , 36.641872 ],
       [26.523924 , 33.11444  ,  8.360636 , 12.717372 , 13.916683 ],
       ...,
       [ 1.8147048, 10.377949 , 34.662144 , 24.054174 , 25.420462 ],
       [35.116352 , 14.995533 , 10.245004 , 22.753975 , 34.579338 ],
       [23.363665 , 13.519805 , 21.845577 , 11.994366 , 17.866734 ]],
      dtype=float32)

In [68]:
import sklearn
acc = sklearn.metrics.accuracy_score(y_train, 
                                     p.round())

In [69]:
acc

0.5277

In [70]:
not_satisfied = []
C_val_not_satisfied = []
W_not_val=[]

In [71]:
c=0
d=0

for i,j,k in zip(p,weights_train,cap_train):
  s= np.dot(i,j)
  #print(s)
  #print(k)
  if s<k or s==k :
    c = c+1
  else:
    not_satisfied.append(i)
    W_not_val.append(j)
    C_val_not_satisfied.append(k)
    d = d+1
print(c)
print(d)

64044
5956


In [58]:
c=0
d=0

for i,j,k in zip(p.round(),weights_train,cap_train):
  s= np.dot(i,j)
  #print(s)
  #print(k)
  if s<k or s==k :
    c = c+1
  else:
    not_satisfied.append(i)
    W_not_val.append(j)
    C_val_not_satisfied.append(k)
    d = d+1
print(c)
print(d)

57142
12858


In [49]:
len(not_satisfied)

20366

In [50]:
pd.DataFrame({'Not Satisfied': not_satisfied,
              'W vals': W_not_val,
     'C': C_val_not_satisfied,
     
    })

Not Satisfied  \
0      [0.8829075, 0.019817233, 1.9334037e-09, 0.3932...   
1      [0.5263564, 2.9870998e-06, 0.9784666, 0.382111...   
2      [0.8099734, 0.51308423, 1.2654652e-14, 2.11877...   
3      [0.00027814507, 0.76967597, 0.6877754, 0.02652...   
4      [0.13444206, 0.024085492, 0.21253893, 0.900926...   
...                                                  ...   
20361                          [0.0, 0.0, 0.0, 0.0, 1.0]   
20362                          [1.0, 1.0, 0.0, 0.0, 1.0]   
20363                          [1.0, 1.0, 1.0, 1.0, 1.0]   
20364                          [0.0, 1.0, 0.0, 0.0, 0.0]   
20365                          [0.0, 0.0, 0.0, 1.0, 1.0]   

                                                  W vals          C  
0      [11.728507, 12.439032, 34.57899, 15.020437, 24...  23.553967  
1      [9.58345, 21.955437, 8.802344, 25.455645, 42.8...  23.180250  
2      [4.737426, 8.74845, 36.192688, 24.541895, 23.8...   6.318098  
3      [42.328396, 12.708107, 35.259235, 37.981365, 1...  36.749237  
4      [8.169544, 17.572681, 10.23879, 11.770866, 24....  25.461775  
...                                                  ...        ...  
20361  [29.462154, 22.363295, 20.921139, 36.063595, 3...  22.602640  
20362  [28.725971, 21.744762, 44.61656, 39.90619, 7.3...  43.143028  
20363  [38.39972, 26.79019, 2.1035643, 20.552551, 3.6...  91.311493  
20364  [41.2227, 4.7748485, 6.290448, 1.3149844, 37.7...   2.595096  
20365  [35.490204, 17.905914, 28.603146, 26.45034, 18...  40.122185  

[20366 rows x 3 columns]

In [101]:
p_test = model.predict([weights_test,prices_test,cap_test])

In [102]:
c=0
d=0

for i,j,k in zip(p_test,weights_test,cap_test):
  s= np.dot(i,j)
  #print(s)
  #print(k)
  if s<k or s==k :
    c = c+1
  else:
    #not_satisfied.append(i)
    #W_not_val.append(j)
    #C_val_not_satisfied.append(k)
    d = d+1
print(c)
print(d)

29563
437


In [103]:
c=0
d=0

for i,j,k in zip(p_test.round(),weights_test,cap_test):
  s= np.dot(i,j)
  #print(s)
  #print(k)
  if s<k or s==k :
    c = c+1
  else:
    #not_satisfied.append(i)
    #W_not_val.append(j)
    #C_val_not_satisfied.append(k)
    d = d+1
print(c)
print(d)

24496
5504


In [194]:
model.save('ContraintLearningNonroundoff23Nov.h5')