In [1]:
import numpy as np
import pandas as pd


In [2]:
df = pd.read_csv('trial.csv')

In [3]:
df

2.73      1.11E-13      2.31E-14  0
0   3.723000  3.660000e-15  2.310000e-14  1
1   1.649700  7.210000e-13  2.310000e-14  0
2   1.658100  5.810000e-09  2.310000e-14  0
3   3.760200  2.690000e-15  2.310000e-14  0
4   0.003798  8.890000e-16  2.310000e-14  1
5   1.678100  3.690000e-15  2.310000e-14  0
6   3.950400  1.660000e-16  2.310000e-14  1
7   3.718600  8.720000e-15  2.310000e-14  0
8   4.583200  8.660000e-17  2.310000e-14  0
9   2.160700  7.360000e-15  2.310000e-14  1
10  4.720600  6.670000e-15  2.310000e-14  1
11  3.110700  2.400000e-14  2.310000e-14  0
12  2.840100  5.680000e-14  2.310000e-14  0
13  1.978000  1.460000e-11  2.310000e-14  0
14  0.713020  5.530000e-14  2.310000e-14  0
15  1.932000  4.490000e-17  2.310000e-14  0
16  2.204600  3.520000e-16  2.310000e-14  1
17  2.627000  9.500000e-14  2.310000e-14  0
18  4.111600  2.590000e-15  2.310000e-14  0
19  5.240100  1.040000e-14  2.310000e-14  0
20  1.089800  9.550000e-13  2.310000e-14  0
21  4.660400  5.260000e-16  2.310000e-14  1
22  4.963500  1.020000e-15  2.310000e-14  1
23  1.324100  6.280000e-15  2.310000e-14  0
24  2.667700  2.290000e-15  2.310000e-14  1
25  2.392900  5.730000e-13  2.310000e-14  0
26  1.511200  1.150000e-13  2.310000e-14  0
27  1.313300  2.450000e-16  2.310000e-14  0
28  0.435960  2.960000e-15  2.310000e-14  0

In [4]:
X = df.iloc[:,:-1].values
#y = df['0.24'].values
y = df.iloc[:,-1:].values

In [5]:
X

array([[3.7230e+00, 3.6600e-15, 2.3100e-14],
       [1.6497e+00, 7.2100e-13, 2.3100e-14],
       [1.6581e+00, 5.8100e-09, 2.3100e-14],
       [3.7602e+00, 2.6900e-15, 2.3100e-14],
       [3.7981e-03, 8.8900e-16, 2.3100e-14],
       [1.6781e+00, 3.6900e-15, 2.3100e-14],
       [3.9504e+00, 1.6600e-16, 2.3100e-14],
       [3.7186e+00, 8.7200e-15, 2.3100e-14],
       [4.5832e+00, 8.6600e-17, 2.3100e-14],
       [2.1607e+00, 7.3600e-15, 2.3100e-14],
       [4.7206e+00, 6.6700e-15, 2.3100e-14],
       [3.1107e+00, 2.4000e-14, 2.3100e-14],
       [2.8401e+00, 5.6800e-14, 2.3100e-14],
       [1.9780e+00, 1.4600e-11, 2.3100e-14],
       [7.1302e-01, 5.5300e-14, 2.3100e-14],
       [1.9320e+00, 4.4900e-17, 2.3100e-14],
       [2.2046e+00, 3.5200e-16, 2.3100e-14],
       [2.6270e+00, 9.5000e-14, 2.3100e-14],
       [4.1116e+00, 2.5900e-15, 2.3100e-14],
       [5.2401e+00, 1.0400e-14, 2.3100e-14],
       [1.0898e+00, 9.5500e-13, 2.3100e-14],
       [4.6604e+00, 5.2600e-16, 2.3100e-14],
       [4.

In [6]:
y

array([[1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0]], dtype=int64)

In [7]:
from sklearn.model_selection import train_test_split

In [8]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=42)

In [15]:
X_train

array([[1.1425e+00, 2.3881e-01, 4.8215e+00, ..., 2.8522e-12, 3.7313e-16,
        1.1909e-13],
       [2.3195e+00, 2.9871e+00, 3.2219e-01, ..., 7.1693e-15, 2.4827e-13,
        1.4627e-14],
       [1.1302e+00, 2.4118e+00, 3.3051e-01, ..., 1.1952e-14, 7.2901e-16,
        1.6531e-13],
       ...,
       [2.1441e-01, 2.1676e-01, 5.3827e+00, ..., 5.2399e-15, 2.1347e-14,
        2.0255e-14],
       [3.4127e-01, 4.3557e+00, 2.8768e+00, ..., 3.7004e-17, 5.0743e-17,
        5.4955e-14],
       [3.1287e+00, 4.2591e+00, 2.9877e+00, ..., 9.5657e-17, 1.6608e-13,
        4.5055e-14]])

In [16]:
y_train

array([[0, 0, 1, ..., 1, 0, 0],
       [0, 1, 0, ..., 1, 0, 0],
       [0, 1, 0, ..., 1, 1, 1],
       ...,
       [0, 0, 1, ..., 1, 1, 0],
       [0, 0, 0, ..., 1, 1, 1],
       [0, 1, 0, ..., 0, 1, 0]], dtype=int64)

In [ ]:
X[0]

## Logistic Regression

In [69]:
from sklearn.linear_model import LogisticRegression
from sklearn.multioutput import MultiOutputClassifier

In [70]:
X[0]

array([3.723e+00, 3.660e-15, 2.310e-14])

In [71]:
clf =(LogisticRegression(random_state=42)).fit(X,y)

C:\Users\venka\Anaconda3\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


In [72]:
#Score for validation data
clf.score(X,y)

0.6896551724137931

In [73]:
#Score for training data
clf.score(X_train,y_train)

ValueError: X has 61 features per sample; expecting 3

## K Nearest Classifiers

In [27]:
from sklearn.neighbors import KNeighborsClassifier

In [28]:
neigh = MultiOutputClassifier(KNeighborsClassifier(n_neighbors=30))

In [29]:
neigh.fit(X_train, y_train)

MultiOutputClassifier(estimator=KNeighborsClassifier(n_neighbors=30))

In [30]:
neigh.score(X_train,y_train)

0.08951118889861233

In [27]:
neigh.score(X_test,y_test)

0.732

## Random Forest Classifier

In [9]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.multioutput import MultiOutputClassifier

In [12]:
forest = RandomForestClassifier(n_estimators=100, random_state=1)
classifier = MultiOutputClassifier(forest, n_jobs=-1)
clf = classifier.fit(X_train, y_train)
classifier.score(X_train,y_train)

1.0

In [11]:
 from sklearn import tree

In [13]:
tree.plot_tree(clf) 

AttributeError: 'MultiOutputClassifier' object has no attribute 'tree_'

In [30]:
X_test[0]

array([7.5837e+00, 2.4300e-19, 3.8000e-13])

In [31]:
y_test[0]

array([0], dtype=int64)

In [32]:
pred = classifier.predict(X_test)

In [33]:
pred[0]

array([1], dtype=int64)

In [34]:
classifier.score(X_test,y_test)

0.6455

In [35]:
print(classifier.predict(X_test))

[[1]
 [0]
 [0]
 ...
 [0]
 [0]
 [0]]


In [36]:
#clf.fit(X_train,y_train)

In [37]:
clf.score(X_train,y_train)

0.7327165895736967

In [38]:
clf.score(X_test,y_test)

0.7495

## Gaussian Naive Bayes Classifier

In [39]:
from sklearn.naive_bayes import GaussianNB

In [40]:
model = GaussianNB()

In [41]:
model.fit(X_train,y_train)

C:\Users\venka\Anaconda3\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


GaussianNB()

In [42]:
model.score(X_train,y_train)

0.7327165895736967

In [43]:
model.score(X_test,y_test)

0.7455

## XGBoost Classifier

In [44]:
from sklearn.ensemble import GradientBoostingClassifier

In [45]:
clf = GradientBoostingClassifier(n_estimators=100, learning_rate=1.0,
...     max_depth=1, random_state=0).fit(X_train, y_train)


C:\Users\venka\Anaconda3\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


In [46]:
clf.score(X_test, y_test)

0.739